main: me.snowman.itemmultiply.ItemMultiply
name: ItemMultiply
author: SnowmanFTW
version: ${project.version}
api-version: 1.16

commands:
  itemmultiply:
    description: Main command for the plugin
    usage: /<command>
    aliases: [im]
